### PR TITLE
add method before the method name

### PR DESCRIPTION
**Pull request by amirjr1378**
for issue #130

### CODE REVIEW

**Comment by Manweill** [comment]
@amirjr1378 
you need add new methodMode. 
eg `methodMode=restful` ?

**Comment by Manweill** [comment]
btw, `restful api` always use `methodNameMode === 'operationId'`

**Comment by amirjr1378** [comment]
> p

but when i use methodNameMode = 'operationId' instead of 'path' it  doesnt generate classes that handles the requests it only create interfaces.

[swagger.zip](https://github.com/Manweill/swagger-axios-codegen/files/6234163/swagger.zip)

**Comment by Manweill** [comment]
because the spec.json do not have operationId.

**Comment by amirjr1378** [comment]
> because the spec.json do not have operationId.

tnx i add operation id and everything is fine.

**Pull request closed without merging**
