### PR TITLE
feat: support additionalProperties for top level entities

### PR DESCRIPTION
**Pull request by will7200**
My implementation of additional properties so they can be types.

### CODE REVIEW

**Comment by Manweill** [comment]
@will7200 
Hey, can you let me see the result of the generation before and after?

**Comment by Manweill** [comment]
@will7200 maybe you should show the changed after your PR.

**Comment by will7200** [comment]
@Manweill 
Examples:
1. If there properties defined on the model it will export an additional type with a union type.
```typescript
export type ResponseWithAdditionalParametersWithAdditionalProperties = ResponseWithAdditionalParameters & {
  [additionalProperties: string]: object;
};
```
2. If there are no properties defined on the model:
```typescript
export interface ResponseWithOnlyAdditionalParameters {
  /**  */
  [additionalProperties: string]: number;
}
```

Now lies the problem of how to use the new type instead of the interface if the model has existing properties

**Comment by Manweill** [comment]
> @Manweill
> Examples:
> 
> 1. If there properties defined on the model it will export an additional type with a union type.
> 
> ```ts
> export type ResponseWithAdditionalParametersWithAdditionalProperties = ResponseWithAdditionalParameters & {
>   [additionalProperties: string]: object;
> };
> ```
> 
> 1. If there are no properties defined on the model:
> 
> ```ts
> export interface ResponseWithOnlyAdditionalParameters {
>   /**  */
>   [additionalProperties: string]: number;
> }
> ```
> 
> Now lies the problem of how to use the new type instead of the interface if the model has existing properties

It will not affect existing code?

**Comment by will7200** [comment]
Yeah its an enhancement and is backwards compatible with your existing code base. If they don't define additional properties or it is set to false it will retain the current behavior.

**Pull request merged**
