### PR TITLE
#69 - Promise result is Any instead of the actual Type in open api v3

### PR DESCRIPTION
**Pull request by denis-pujdak-adm-it**
fix of the issue #69 

please see the last commit. Could not figure out why it shows all those previous commits.

### CODE REVIEW

**Comment by Manweill** [comment]
repeated  commit

**Comment by denis-pujdak-adm-it** [comment]
>> repeated commit

yeah, I have no Idea why it looks like that. By the way the actual change is this https://github.com/Manweill/swagger-axios-codegen/pull/70/commits/9c9ef478219ea13b39eb84ecc804b1ce3baa5917

**Comment by Manweill** [comment]
> > > repeated commit
> 
> yeah, I have no Idea why it looks like that. I thought I did rebase. By the way the actual change is this [9c9ef47](https://github.com/Manweill/swagger-axios-codegen/commit/9c9ef478219ea13b39eb84ecc804b1ce3baa5917)

You need merge first or rebase  and coding on a new branch

**Comment by denis-pujdak-adm-it** [comment]
Closing and creating a new PR. Probably github is broken.

**Pull request closed without merging**
