### PR TITLE
throw execeptions that can be catched by user program

### PR DESCRIPTION
**Pull request by lamuertepeluda**
Hi,

I try to address the problem that I mentioned [here](https://github.com/Manweill/swagger-axios-codegen/issues/13#issuecomment-468596668), in the first part of the comment.

Now if some error occurs when generating the api, they are not swallowed by codegen but instead they are thrown (after cleaning cache and other stuff) so that a user program can exit with error status.

### CODE REVIEW

**Comment by Manweill** [comment]
@lamuertepeluda add `package-lock.json` on .gitignore

**Comment by lamuertepeluda** [comment]
done

**Comment by Manweill** [comment]
emmm, remove it? just use yarn

**Comment by lamuertepeluda** [comment]
ok sorry I didn't get you were using yarn... reverting to yarn soon

**Comment by lamuertepeluda** [comment]
done now

**Pull request merged**
